export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const BUY_PRODUCT = "BUY_PRODUCT";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const CHECKOUT = "CHECKOUT";
export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
